name: Small Bits
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

gems:
  - jekyll-sitemap
